### ISSUE TITLE
Is this a error to worry about?

### ISSUE THREAD

**Issue by maserowik** [thomasjacquin/allsky-website#70] opened 2022-01-12 15:21 UTC
![image](https://user-images.githubusercontent.com/25713782/149168970-5586e66a-85a9-4d44-8538-a379fb86f6f2.png)

**Comment by EricClaeys** [comment] 2022-01-15 06:36
@maserowik No, since it's only a Notice and things work.  However, I don't like message in that log file so I just submitted a fix to eliminate the message.  The problem is in one of the files in the Allsky-portal package, so I'm closing this Issue since it's in Allsky-website.  There's no way you would have known which package caused the error.  Thanks for letting me know about it.

**Closed by EricClaeys** 2022-01-15 06:36 UTC
Labels: bug
